# This file is for experimenting and seeing what works and how. All the final code will be available in main.py.
- Now I'm using the simplegmail library to parse mails.
- Wish me luck monekeys.

In [50]:
from simplegmail import Gmail

In [51]:
gmail = Gmail(creds_file="token.pickle", client_secret_file="credentials.json")

In [53]:
messages = gmail.get_messages(query = "newer_than:200d")

In [54]:
len(messages)

517

In [57]:
mtypes = set()
for message in messages:
    try:
        mtypes.add(message.headers["Content-Type"].split(";")[0]) # get mtypes. 
    except KeyError:
        pass # just not going to handle this.
# this library returns content type as a string, such that:
# "content-type: multipart/...; boundary: xxx". so when we split at semicolon, and take first element of the list,
# we get content type yessir ^^

In [58]:
mtype_classified = {m: [] for m in mtypes} # dict for classifying

In [60]:
for message in messages:
    try:
        mtype_classified[message.headers["Content-Type"].split(";")[0]].append(message)
    except KeyError:
        pass

In [61]:
mtype_classified["multipart/related"] # example

[Message(to: undisclosed-recipients:;, from: Elliott P <elliott@blueprint.hackclub.com>, id: 19e2e2cbf90369b7),
 Message(to: syedmrihaan@gmail.com, from: ServiceNow Developer Program <devportalprod@service-now.com>, id: 19c7f45ff9daa406),
 Message(to: syedmrihaan@gmail.com, from: ServiceNow Developer Program <devportalprod@service-now.com>, id: 19c245241806ecb5),
 Message(to: Muhammad Rihaan <syedmrihaan@gmail.com>, from: Nishad Meharaj <nishad.meharaj@gmail.com>, id: 19bdb32db04f92e9),
 Message(to: Muhammad Rihaan <syedmrihaan@gmail.com>, from: Nishad Meharaj <nishad.meharaj@gmail.com>, id: 19b935b035166aa8),
 Message(to: undisclosed-recipients:;, from: Elliott P <elliott@blueprint.hackclub.com>, id: 19e2e2cbf90369b7),
 Message(to: syedmrihaan@gmail.com, from: ServiceNow Developer Program <devportalprod@service-now.com>, id: 19c7f45ff9daa406),
 Message(to: syedmrihaan@gmail.com, from: ServiceNow Developer Program <devportalprod@service-now.com>, id: 19c245241806ecb5),
 Message(to: Muhammad Rihaan <syedmrihaan@gmail.com>, from: Nishad Meharaj <nishad.meharaj@gmail.com>, id: 19bdb32db04f92e9),
 Message(to: Muhammad Rihaan <syedmrihaan@gmail.com>, from: Nishad Meharaj <nishad.meharaj@gmail.com>, id: 19b935b035166aa8),
 Message(to: Muhammad Rihaan <syedmrihaan@gmail.com>, from: Muhammad Rihaan <syedmrihaan@gmail.com>, id: 19af358edb0c9f3e)]

In [62]:
message_count = 0

for key in mtype_classified.keys():
    for message in mtype_classified[key]:
        message_count += 1

In [63]:
message_count

996

### ***Nice, it's working.***

btw im borrowing this plan from the previous notebook.

***Data Collection***
- Collect message ID 
- Collect sender name 
- Collect sender domain, sender local part 
- Collect combined text(subject + body) 
- Collect word count of body 
- Collect number of numerical characters(digits) in body. 
- Collect link count(useful for promotional mails or maybe school mails? idk) 
- Collect currency count(useful for promotional i think) 
- Collect presence of otp-like numbers 
- Collect exclamation mark count(spammy emails) 
- Also record contains_html, and contains_plain.
- Also record presence of html structures like image_count, button_count, etc...

***Final Dataframe***
- Sender info 
- Combined text
- Word count
- Digit count
- Mail folder
- Message ID(DO NOT TRAIN ON THIS)

***Marking Targets***
- Perform unsupervised KMeans to get clusters.

***Model and Final pipeline***
- Gaussian naive bayes.

In [64]:
"""

- Collect message ID ✅
- Collect sender name ✅
- Collect sender domain, sender local part ✅
- Collect combined text(subject + body) ✅
- Collect word count of body ✅
- Collect number of numerical characters(digits) in body. ✅
- Collect link count(useful for promotional mails or maybe school mails? idk) ✅
- Collect currency count(useful for promotional i think) ✅
- Collect presence of otp-like numbers ✅
- Collect exclamation mark count(spammy emails) ✅
- Also record contains_html, and contains_plain. ✅

"""

from email.utils import parseaddr
import html, re
from bs4 import BeautifulSoup

# function to clean mails of special chars

def cleaner(text):
    cleaned = html.unescape(text)
    cleaned = re.sub(r'[\u200c\u200b\u200d\ufeff\xad]', "", cleaned) 
    # [] => match any one char, an since every char is unicode, regex treats \u200c(for eg) as a single char
    cleaned = " ".join(cleaned.split())
    return cleaned

# quick function to use expressions based on which type of msg we have

def parse_mail(msg):
    msg_id = msg.id
    sender = msg.sender
    sender_name, sender_addr = parseaddr(sender)
    sender_local, sender_domain = sender_addr.rsplit("@", 1)
    subject = cleaner(msg.subject)

    contains_html, contains_plain = int(bool(msg.html)), int(bool(msg.plain))

    soup = BeautifulSoup(msg.html, "html.parser") if contains_html else "" # for html

    body = re.sub(r"https?://\S+", "",cleaner(msg.plain)) if not contains_html else cleaner(soup.get_text(strip = True, separator = " "))# to remove links
    combined_text = f"{subject} {body}"

    word_count = len(body.split())

    digit_count = sum([char.isdigit() for char in body])

    link_count = len(soup.find_all("a", href=True)) if contains_html else re.findall(r"https?://S+", body)

    currency_count = sum([char in ["₹", "$"] for char in body])

    otp_count = len(re.findall(r"\b\d{4,8}\b", body))

    exclamation_count = sum([char == "!" for char in body])

    image_count = 0 if not contains_html else len(soup.find_all("img"))

    # final record

    record = {"id": msg_id,
              "contains_html": contains_html,
              "contains_plain_text": contains_plain,
              "sender_name": sender_name,
              "sender_local": sender_local,
              "sender_address": sender_addr,
              "comb_text": combined_text if len(combined_text.strip()) > 0 else None, # because empty records are noise creators
              "word_count": word_count,
              "digit_count": digit_count,
              "link_count": link_count,
              "currency_count": currency_count,
              "otp_count": otp_count,
              "exclamation_count": exclamation_count,
              "image_count": image_count
              }
    
    return record

In [65]:
records = [parse_mail(message) for message in messages][:]

In [66]:
import pandas as pd

df = pd.DataFrame(records).set_index("id").dropna()

In [67]:
df.head()

,contains_html,contains_plain_text,sender_name,sender_local,sender_address,comb_text,word_count,digit_count,link_count,currency_count,otp_count,exclamation_count,image_count
id,,,,,,,,,,,,,
19ec1cd1706a637f,1,1,Google,noreply-accounts,noreply-accounts@google.com,You shared some Google Account data with Slack...,295,33,3,0,3,0,12
19ec1be81dcff6cc,1,1,Hack Club,auth,auth@hackclub.com,752-267 is your Hack Club login code Your code...,73,18,1,0,0,2,1
19ec1b94b050434a,1,1,Stella Clark,stella,stella@joinspeakup.com,Invitation | Research Publication Fellowship M...,584,33,1,0,3,2,1
19ec04f3f568b7a0,1,0,RVRG FM Helpdesk,donotreply,donotreply@apnacomplex.com,[Rainbow Vistas @ Rock Garden] New Notice: UPD...,156,17,8,0,2,1,8
19ebe64e13ebe24d,1,1,Stephen from Render,hello,hello@render.com,The easiest way to launch scalable web service...,174,3,5,0,0,0,1

In [68]:
df[df["comb_text"].str.len() == 0]

Empty DataFrame
Columns: [contains_html, contains_plain_text, sender_name, sender_local, sender_address, comb_text, word_count, digit_count, link_count, currency_count, otp_count, exclamation_count, image_count]
Index: []

### **It's been a few hours.**

### Lets grind :)

# ***Plan***
- Perform TF-IDF vectorization in a pipeline probably
- Perform kmeans unsupervised.
- If i get this to work then 90% of my project is done ^^

In [69]:
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [70]:
preprocessor = ColumnTransformer([
    ("tf-idf", TfidfVectorizer(
        stop_words = "english", #this means to remove english filler wordds(like the, a, and,etc...)
        max_features = 2500,
        min_df = 5,
        max_df = 0.95,
        ngram_range = (1, 3)
        
    ), "comb_text"),
    ("cats", OneHotEncoder(drop = "first", sparse_output=False), ["sender_name", "sender_local", "sender_address"]),
    ("numerical", StandardScaler(), make_column_selector(dtype_include="int64"))
])

In [71]:
vectorized_df = preprocessor.fit_transform(df)

### **Done with TF-IDF**

# **Unsupervised Kmeans time**

In [72]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [73]:
best_score = -1
best_k = 0
best_kmeans = None

for k in range(3, 15):
    kmeans = KMeans(
        n_clusters = k,
        random_state = 11,
        n_init = 10
    )

    labels = kmeans.fit_predict(vectorized_df)
    score = silhouette_score(vectorized_df, labels) # use silhouette score to judge efficiency of k clusters

    if score > best_score:
        best_score = score
        best_k = k
        best_kmeans = kmeans

In [74]:
best_kmeans

KMeans(n_clusters=3, n_init=10, random_state=11)

In [75]:
best_k, best_score

(3, 0.38413246393146366)

In [76]:
clusters = best_kmeans.predict(vectorized_df)

In [77]:
df["cluster"] = clusters.astype("str") # as string so that its easier to handle in pipeline.

In [78]:
df.cluster

id
19ec1cd1706a637f    1
19ec1be81dcff6cc    1
19ec1b94b050434a    1
19ec04f3f568b7a0    1
19ebe64e13ebe24d    1
                   ..
19acd8fb52a8b03f    1
19acd8d174980999    1
19ac82a43eeea155    1
19ac590c5057cf64    1
19ac41b2e9094852    1
Name: cluster, Length: 490, dtype: str

In [79]:
[str(c) for c in sorted(clusters)][:]

['0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '2',
 '2',
 '2',
 '2']

In [80]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

new_preprocessor = ColumnTransformer([
    ("tf-idf", TfidfVectorizer(
        stop_words = "english", #this means to remove english filler wordds(like the, a, and,etc...)
        max_features = 2500,
        
    ), "comb_text"),
    ("cats", OneHotEncoder(drop = "first", sparse_output=False), ["sender_name", "sender_local", "sender_address"]),
    ("numerical", StandardScaler(), make_column_selector(dtype_include="int64")),
    ("cluster", OrdinalEncoder(categories=[[str(c) for c in np.unique(clusters)][:]]), ["cluster"])
])

In [81]:
clustered_df = new_preprocessor.fit_transform(df)

In [82]:
df[["comb_text", "cluster"]].head(n = 15)

                                                          comb_text cluster
id
19ec1cd1706a637f  You shared some Google Account data with Slack...       1
19ec1be81dcff6cc  752-267 is your Hack Club login code Your code...       1
19ec1b94b050434a  Invitation | Research Publication Fellowship M...       1
19ec04f3f568b7a0  [Rainbow Vistas @ Rock Garden] New Notice: UPD...       1
19ebe64e13ebe24d  The easiest way to launch scalable web service...       1
19ebd34a54c77f04  NotARoomba sent you messages Hack Club 112,958...       0
19ebc7967c7afafb  Competition Launch: AI Agent Security: Multi-S...       1
19ebbd68603657b0  💡 Explore GitGuardian Resources 2/2 Master sec...       1
19eb92c3489aca11  New privacy settings for Search services and G...       1
19eb6f7a1257e8bf  NASA EXPRESS -- Your STEM Connection for June ...       0
19eb6705953ceb64  You shared some Google Account data with Claud...       1
19eb66f9dadefdbe  Your account has been suspended Hello, Our tea...       1
19eb26be08090193  Invitation | Pathways to and through Medicine ...       1
19eb1311a909ccdf  Future Doctors Fellowship Special Scholarship ...       1
19ead501767d580b  Bring the band back together with Spotify Prem...       1

In [83]:
new_clusters = dict()
for cluster in df["cluster"].unique():
    print("=" * 50)
    print(f"CLUSTER {cluster}")

    text = df.loc[
        df["cluster"] == cluster,
        "comb_text"
    ]
    vectorizer = preprocessor.named_transformers_["tf-idf"]
    vectorized_text = vectorizer.transform(text)

    mean_score = vectorized_text.mean(axis = 0)

    top_words = (
        pd.Series(
            mean_score.A1,
            index = vectorizer.get_feature_names_out()
        )
        .sort_values(ascending=False)
        .head(10)
    )

    print(top_words)

    new_clusters[cluster] = input("The program detected a lot of mails with these key words being quite frequent. These mails will be moved into a particular folder, and new incoming mails will be sorted on the basis of these keywords. What would you like to name this folder? ")

==================================================
CLUSTER 1
account     0.033199
email       0.026893
app         0.026725
com         0.026465
code        0.026238
download    0.025478
session     0.024403
ai          0.022339
payment     0.021760
google      0.021349
dtype: float64
==================================================
CLUSTER 0
nasa             0.302144
stem             0.082525
gov              0.081147
nasa gov         0.081147
apple            0.078991
space            0.074925
science          0.059226
resources        0.055132
learning         0.052664
opportunities    0.049391
dtype: float64
==================================================
CLUSTER 2
mo          0.326307
apple       0.291806
00          0.181080
00 mo mo    0.175045
mo mo       0.170593
00 mo       0.166666
buy         0.154928
trade       0.152998
card        0.126459
cashback    0.121909
dtype: float64

In [84]:
new_clusters

{'1': 'google account stuff', '0': 'stem learning', '2': 'spam'}

In [85]:
df["cluster"] = df["cluster"].str.replace(new_clusters, None)

In [86]:
df.head(10)

,contains_html,contains_plain_text,sender_name,sender_local,sender_address,comb_text,word_count,digit_count,link_count,currency_count,otp_count,exclamation_count,image_count,cluster
id,,,,,,,,,,,,,,
19ec1cd1706a637f,1,1,Google,noreply-accounts,noreply-accounts@google.com,You shared some Google Account data with Slack...,295,33,3,0,3,0,12,google account stuff
19ec1be81dcff6cc,1,1,Hack Club,auth,auth@hackclub.com,752-267 is your Hack Club login code Your code...,73,18,1,0,0,2,1,google account stuff
19ec1b94b050434a,1,1,Stella Clark,stella,stella@joinspeakup.com,Invitation | Research Publication Fellowship M...,584,33,1,0,3,2,1,google account stuff
19ec04f3f568b7a0,1,0,RVRG FM Helpdesk,donotreply,donotreply@apnacomplex.com,[Rainbow Vistas @ Rock Garden] New Notice: UPD...,156,17,8,0,2,1,8,google account stuff
19ebe64e13ebe24d,1,1,Stephen from Render,hello,hello@render.com,The easiest way to launch scalable web service...,174,3,5,0,0,0,1,google account stuff
19ebd34a54c77f04,1,1,Hack Club (via Slack),notification,notification@slack.com,"NotARoomba sent you messages Hack Club 112,958...",480,75,22,0,2,20,40,stem learning
19ebc7967c7afafb,1,1,Kaggle,no-reply,no-reply@kaggle.com,Competition Launch: AI Agent Security: Multi-S...,213,20,3,1,3,0,2,google account stuff
19ebbd68603657b0,1,1,Dwayne McDaniel,dwayne.mcdaniel,dwayne.mcdaniel@gitguardian.com,💡 Explore GitGuardian Resources 2/2 Master sec...,291,0,7,0,0,0,1,google account stuff
19eb92c3489aca11,1,1,Google,google-noreply,google-noreply@google.com,New privacy settings for Search services and G...,502,13,5,0,3,0,1,google account stuff
19eb6f7a1257e8bf,1,1,NASA STEM Engagement,hq-stem-communications,hq-stem-communications@mail.nasa.gov,NASA EXPRESS -- Your STEM Connection for June ...,783,19,52,0,2,2,38,stem learning